import JSZip from "jszip";
import { describe, expect, it } from "vitest";
import { buildManifest, buildZip, csvField, planExport, scriptUsed, selectFileName, takeFileName, type ExportInput } from "@/lib/export";
import { parseScript } from "@/lib/parser";
import { EXAMPLE_SCRIPT } from "@/lib/example";

const parsed = parseScript(EXAMPLE_SCRIPT);
const bytes = (n: number) => new Uint8Array([0xff, 0xfb, n]);

function input(mode: ExportInput["mode"]): ExportInput {
  const takes = new Map<string, { take: number; seed: number; blob: Uint8Array }[]>();
  takes.set("S1-004", [
    { take: 2, seed: 222, blob: bytes(2) },
    { take: 1, seed: 111, blob: bytes(1) },
  ]);
  takes.set("S0-001", [{ take: 1, seed: 7, blob: bytes(7) }]);
  return {
    video: parsed.video,
    chunks: parsed.chunks,
    takes,
    picks: { "S1-004": 2 },
    script: EXAMPLE_SCRIPT,
    mode,
    now: new Date("2026-10-03T12:00:00.000Z"),
  };
}

describe("file names", () => {
  it("follow the documented pattern", () => {
    const c = parsed.chunks[4];
    expect(takeFileName("worst-jobs-medieval", c, c.model, 3)).toBe("worst-jobs-medieval_S1-004_v3_t3.mp3");
    expect(selectFileName("worst-jobs-medieval", c, c.model)).toBe("worst-jobs-medieval_S1-004_v3.mp3");
  });
});

describe("csvField", () => {
  it("escapes commas, quotes, newlines and edge whitespace", () => {
    expect(csvField("plain")).toBe("plain");
    expect(csvField("a, b")).toBe('"a, b"');
    expect(csvField('He said "no"')).toBe('"He said ""no"""');
    expect(csvField("line\nbreak")).toBe('"line\nbreak"');
    expect(csvField(" pad")).toBe('" pad"');
    expect(csvField(null)).toBe("");
    expect(csvField(false)).toBe("false");
    expect(csvField(12)).toBe("12");
  });
});

describe("manifest", () => {
  it("has the right columns and one row per chunk", () => {
    const i = input("both");
    const csv = buildManifest(i.chunks, i.takes, i.picks);
    const lines = csv.trimEnd().split("\r\n");
    expect(lines[0]).toBe(
      "chunk_id,story,story_title,model,climax,take_count,picked_take,pause_after,characters,seed_per_take,text",
    );
    expect(lines).toHaveLength(1 + parsed.chunks.length);
    expect(lines[1]).toBe("S0-001,S0,Cold Open,v2,false,1,,,57,t1:7,\"Today, we're going over the worst jobs in medieval times.\"");
    expect(lines[2]).toMatch(/^S1-001,S1,Richard the Raker,v2,false,0,,1,18,,Richard the Raker\.$/);
    expect(lines[5]).toBe(
      "S1-004,S1,Richard the Raker,v3,true,2,2,,57,t1:111|t2:222,The floorboards groan. [gasps] And then... they give way.",
    );
  });
});

describe("script_used.txt", () => {
  it("starts with the header line", () => {
    const s = scriptUsed("body", new Date("2026-10-03T12:00:00.000Z"));
    expect(s.split("\n")[0]).toBe("Generated by Narrator's Desk — 2026-10-03T12:00:00.000Z");
    expect(s.endsWith("body")).toBe(true);
  });
});

describe("planExport", () => {
  it("both: sorted takes, selects, manifest, script", () => {
    const { files, takeCount, selectCount } = planExport(input("both"));
    expect(files.map((f) => f.path)).toEqual([
      "worst-jobs-medieval/takes/worst-jobs-medieval_S0-001_v2_t1.mp3",
      "worst-jobs-medieval/takes/worst-jobs-medieval_S1-004_v3_t1.mp3",
      "worst-jobs-medieval/takes/worst-jobs-medieval_S1-004_v3_t2.mp3",
      "worst-jobs-medieval/selects/worst-jobs-medieval_S1-004_v3.mp3",
      "worst-jobs-medieval/manifest.csv",
      "worst-jobs-medieval/script_used.txt",
    ]);
    expect([takeCount, selectCount]).toEqual([3, 1]);
  });

  it("all takes only", () => {
    const paths = planExport(input("all")).files.map((f) => f.path);
    expect(paths.some((p) => p.includes("/selects/"))).toBe(false);
    expect(paths.filter((p) => p.includes("/takes/"))).toHaveLength(3);
  });

  it("selects only", () => {
    const paths = planExport(input("selects")).files.map((f) => f.path);
    expect(paths.some((p) => p.includes("/takes/"))).toBe(false);
    expect(paths.filter((p) => p.includes("/selects/"))).toHaveLength(1);
  });

  it("ignores a pick with no matching take", () => {
    const i = input("selects");
    i.picks = { "S1-004": 9 };
    expect(planExport(i).selectCount).toBe(0);
  });
});

describe("buildZip", () => {
  it("produces a zip with the expected tree and contents", async () => {
    const progress: number[] = [];
    const data = await buildZip(input("both"), { type: "uint8array", onProgress: (p) => progress.push(p) });
    const zip = await JSZip.loadAsync(data);
    const names = Object.keys(zip.files).filter((n) => !zip.files[n].dir).sort();
    expect(names).toEqual([
      "worst-jobs-medieval/manifest.csv",
      "worst-jobs-medieval/script_used.txt",
      "worst-jobs-medieval/selects/worst-jobs-medieval_S1-004_v3.mp3",
      "worst-jobs-medieval/takes/worst-jobs-medieval_S0-001_v2_t1.mp3",
      "worst-jobs-medieval/takes/worst-jobs-medieval_S1-004_v3_t1.mp3",
      "worst-jobs-medieval/takes/worst-jobs-medieval_S1-004_v3_t2.mp3",
    ]);
    const select = await zip.file("worst-jobs-medieval/selects/worst-jobs-medieval_S1-004_v3.mp3")!.async("uint8array");
    expect(Array.from(select)).toEqual([0xff, 0xfb, 2]);
    const script = await zip.file("worst-jobs-medieval/script_used.txt")!.async("string");
    expect(script.startsWith("Generated by Narrator's Desk — 2026-10-03T12:00:00.000Z")).toBe(true);
    expect(progress.at(-1)).toBe(100);
  });
});
