import JSZip from "jszip";
import type { Chunk, Model } from "./types";

export type ExportMode = "all" | "selects" | "both";

export type ExportTake = { take: number; seed: number; blob: Blob | Uint8Array };

export type ExportInput = {
  video: string;
  chunks: Chunk[];
  /** chunkId → fresh takes only */
  takes: Map<string, ExportTake[]>;
  /** chunkId → picked take number */
  picks: Record<string, number>;
  script: string;
  mode: ExportMode;
  now?: Date;
};

export function takeFileName(video: string, chunk: Pick<Chunk, "id">, model: Model, take: number): string {
  return `${video}_${chunk.id}_${model}_t${take}.mp3`;
}

export function selectFileName(video: string, chunk: Pick<Chunk, "id">, model: Model): string {
  return `${video}_${chunk.id}_${model}.mp3`;
}

/** RFC 4180 field escaping. */
export function csvField(value: string | number | boolean | null | undefined): string {
  if (value == null) return "";
  const s = String(value);
  return /[",\r\n]/.test(s) || /^\s|\s$/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export const MANIFEST_COLUMNS = [
  "chunk_id",
  "story",
  "story_title",
  "model",
  "climax",
  "take_count",
  "picked_take",
  "pause_after",
  "characters",
  "seed_per_take",
  "text",
] as const;

export function buildManifest(
  chunks: Chunk[],
  takes: Map<string, { take: number; seed: number }[]>,
  picks: Record<string, number>,
): string {
  const rows = [MANIFEST_COLUMNS.join(",")];
  for (const c of chunks) {
    const list = [...(takes.get(c.id) ?? [])].sort((a, b) => a.take - b.take);
    rows.push(
      [
        c.id,
        `S${c.story}`,
        c.storyTitle,
        c.model,
        c.climax,
        list.length,
        picks[c.id] ?? "",
        c.pauseAfter ?? "",
        c.chars,
        list.map((t) => `t${t.take}:${t.seed}`).join("|"),
        c.text,
      ]
        .map(csvField)
        .join(","),
    );
  }
  return rows.join("\r\n") + "\r\n";
}

export function scriptUsed(script: string, now: Date = new Date()): string {
  return `Generated by Narrator's Desk — ${now.toISOString()}\n\n${script}`;
}

/** Lists every file in the zip, in order, without touching any audio. */
export function planExport(input: ExportInput): { files: { path: string; source: ExportTake | null }[]; takeCount: number; selectCount: number } {
  const { video, chunks, takes, picks, mode } = input;
  const root = `${video}/`;
  const files: { path: string; source: ExportTake | null }[] = [];
  let takeCount = 0;
  let selectCount = 0;
  if (mode !== "selects") {
    for (const c of chunks) {
      for (const t of [...(takes.get(c.id) ?? [])].sort((a, b) => a.take - b.take)) {
        files.push({ path: `${root}takes/${takeFileName(video, c, c.model, t.take)}`, source: t });
        takeCount++;
      }
    }
  }
  if (mode !== "all") {
    for (const c of chunks) {
      const pick = picks[c.id];
      const t = pick == null ? undefined : takes.get(c.id)?.find((x) => x.take === pick);
      if (!t) continue;
      files.push({ path: `${root}selects/${selectFileName(video, c, c.model)}`, source: t });
      selectCount++;
    }
  }
  files.push({ path: `${root}manifest.csv`, source: null });
  files.push({ path: `${root}script_used.txt`, source: null });
  return { files, takeCount, selectCount };
}

export async function buildZip<T extends "blob" | "uint8array" = "blob">(
  input: ExportInput,
  opts: { type?: T; onProgress?: (percent: number) => void } = {},
): Promise<T extends "uint8array" ? Uint8Array : Blob> {
  const zip = new JSZip();
  const { files } = planExport(input);
  const manifest = buildManifest(input.chunks, input.takes, input.picks);
  const script = scriptUsed(input.script, input.now);
  for (const f of files) {
    if (f.source) {
      // MP3 is already compressed; STORE avoids wasted CPU on phones.
      zip.file(f.path, f.source.blob, { binary: true, compression: "STORE" });
    } else if (f.path.endsWith("manifest.csv")) {
      zip.file(f.path, manifest);
    } else {
      zip.file(f.path, script);
    }
  }
  const result = await zip.generateAsync(
    { type: opts.type ?? "blob", streamFiles: true, compression: "DEFLATE", mimeType: "application/zip" },
    (meta) => opts.onProgress?.(meta.percent),
  );
  return result as T extends "uint8array" ? Uint8Array : Blob;
}
